### ISSUE TITLE
validator package causing errors

### ISSUE THREAD

**Issue by Volition42** [ruslanzharkov/nodejs-shopping-cart#11]
In app.js on line 34 is causing an error when I try to run this project. If I comment that out the app runs until I try to create a new account. Then I get an error on config/passport.js on line 25 stating the function does not exist. I'm very interested in learning from this project. Please update your code to use the current specs of the validator package. Here is a link to the documentation for validator: https://express-validator.github.io/docs/guides/getting-started

**Comment by ruslanzharkov** [comment]
Hello,

thanks a lot for mentioning the problem.
I will do my best to update the project as soon as I can 🙂

**Comment by ruslanzharkov** [comment]
Hey @Volition42 I've fixed the problem with the application running, hope you will be able to run the app.
Please be aware there are some issues with sign-up/sign-in features, I will try to solve them as well in a short period of time.

**Comment by ruslanzharkov** [comment]
Hey @Volition42 , the problem with sign-in and sign-up is also fixed 🙂
